// irregular-atlas — animated atlas-cell selector driven by a
// BufferSlot. Demonstrates the extras-pool path end-to-end without
// needing an actual atlas texture: each cell's color is derived
// procedurally from the cell index, so any consumer that swaps in
// a real texture sample only has to replace the inline color
// computation below with a `texture_pool_sample` call.
//
// MaterialData (auto-generated by the wrapper) exposes:
//   frames_offset: u32   // start word in the extras pool
//   frames_length: u32   // length in u32 words (= cells * 4)
//   frame_rate:    f32   // uniform from material.json
//
// Each cell is 4 words: vec4<f32>(x, y, w, h) packed little-endian.
let coords_f = vec2<f32>(f32(input.coords.x), f32(input.coords.y));
let dims_f = vec2<f32>(f32(input.screen_dims.x), f32(input.screen_dims.y));
let uv = coords_f / dims_f;

let fg = frame_globals_from_raw(frame_globals_raw);

let cell_count = input.material.frames_length / 4u;
var color = vec3<f32>(0.0, 0.0, 0.0);
if (cell_count == 0u) {
    // No frames bound (BufferSlot empty) — solid pink so the
    // author notices the missing data immediately.
    color = vec3<f32>(0.9, 0.3, 0.7);
} else {
    // Pick a cell by quantizing time to the configured frame rate.
    let cell_index = u32(fg.time * input.material.frame_rate) % cell_count;
    let base = input.material.frames_offset + cell_index * 4u;
    let rect = vec4<f32>(
        extras_load_f32(base + 0u),
        extras_load_f32(base + 1u),
        extras_load_f32(base + 2u),
        extras_load_f32(base + 3u),
    );

    // Only shade pixels whose UV falls inside the selected rect.
    // Pixels outside fall back to a dim background so the cell
    // boundary is visible against the preview canvas.
    let inside_x = uv.x >= rect.x && uv.x < rect.x + rect.z;
    let inside_y = uv.y >= rect.y && uv.y < rect.y + rect.w;
    if (inside_x && inside_y) {
        // Local UV within the cell, used to give each cell a subtle
        // diagonal gradient instead of a flat fill (so the eye
        // perceives the orientation of the cell).
        let local_uv = vec2<f32>(
            (uv.x - rect.x) / rect.z,
            (uv.y - rect.y) / rect.w,
        );
        // Procedural color: cycle hue around the color wheel per
        // cell index; modulate by a gradient across the cell. A
        // real consumer replaces this with a texture_pool_sample
        // at `rect`'s UV region.
        let hue = f32(cell_index) / f32(cell_count);
        let r = 0.5 + 0.5 * sin(hue * 6.2831853 + 0.0);
        let g = 0.5 + 0.5 * sin(hue * 6.2831853 + 2.0944);
        let b = 0.5 + 0.5 * sin(hue * 6.2831853 + 4.1888);
        let gradient = 0.7 + 0.3 * (local_uv.x + local_uv.y) * 0.5;
        color = vec3<f32>(r, g, b) * gradient;
    } else {
        color = vec3<f32>(0.06, 0.06, 0.08);
    }
}

return OpaqueShadingOutput(color, 1.0);
