name = "untitled.awsm"
custom_materials = []
animations = []

[environment]
skybox = "built_in_default"
specular = "built_in_default"
irradiance = "built_in_default"

[shadows]
sscs_enabled = false
sscs_step_count = 16
sscs_step_world = 0.03999999910593033
sscs_thickness = 0.05000000074505806
sscs_directional_darkening = 0.3499999940395355
sscs_punctual_darkening = 0.8999999761581421
atlas_size = 4096
evsm_atlas_size = 2048
evsm_exponent = 10.0
evsm_blur_radius = 6
max_point_shadows = 8
point_shadow_resolution = 1024
debug_cascade_colors = false

[post_process]
tonemapping = "khronos_neutral_pbr"
bloom = false
dof = false
exposure = 0.0
bloom_threshold = 1.0
bloom_knee = 0.5
bloom_intensity = 1.0
bloom_scatter = 1.0

[post_process.ssr]
enabled = true
intensity = 1.0
max_distance = 120.0
thickness = 0.004999999888241291
max_steps = 128
spread_cutoff = 0.6000000238418579
edge_fade = 0.10000000149011612
resolution_scale = 1.0
temporal = false
temporal_weight = 0.8999999761581421

[assets.00000000-0000-4000-8000-000000000010]
gltf_material_asset_ids = []
gltf_image_asset_ids = []
content_hash = ""

[assets.00000000-0000-4000-8000-000000000010.source.mesh.primitive.sphere]
radius = 0.800000011920929
segments_long = 48
segments_lat = 32

[assets.00000000-0000-4000-8000-000000000001]
gltf_material_asset_ids = []
gltf_image_asset_ids = []
content_hash = ""

[assets.00000000-0000-4000-8000-000000000001.source.mesh.primitive.plane]
width = 400.0
depth = 400.0
segments_x = 1
segments_z = 1

[assets.00000000-0000-4000-8000-000000000011]
gltf_material_asset_ids = []
gltf_image_asset_ids = []
content_hash = ""

[assets.00000000-0000-4000-8000-000000000011.source.mesh.primitive.box]
dims = [
    1.0,
    1.7999999523162842,
    1.0,
]

[assets.00000000-0000-4000-8000-000000000013]
gltf_material_asset_ids = []
gltf_image_asset_ids = []
content_hash = ""

[assets.00000000-0000-4000-8000-000000000013.source.mesh.primitive.sphere]
radius = 0.800000011920929
segments_long = 48
segments_lat = 32

[assets.00000000-0000-4000-8000-000000000012]
gltf_material_asset_ids = []
gltf_image_asset_ids = []
content_hash = ""

[assets.00000000-0000-4000-8000-000000000012.source.mesh.primitive.torus]
radius = 1.0
thickness = 0.05999999865889549
segments_major = 64
segments_minor = 16

[mixer]
layers = []

[[nodes]]
id = "99caff01-4e75-4a86-adac-a552cfadf9d8"
name = "Directional Light"
locked = false
visible = true
prefab = false
children = []

[nodes.transform]
translation = [
    0.0,
    0.0,
    0.0,
]
rotation = [
    -0.4226182699203491,
    0.0,
    0.0,
    0.9063077569007874,
]
scale = [
    1.0,
    1.0,
    1.0,
]

[nodes.kind.light.directional]
color = [
    1.0,
    1.0,
    1.0,
]
intensity = 1.0

[nodes.kind.light.directional.shadow]
cast = true
depth_bias = 0.0010000000474974513
normal_bias = 0.0
resolution = 2048
hardness = "soft"
pcss_penumbra_scale = 1.0
kernel_slack = 0.0
shadow_samples = 16
max_distance = 0.0
cascade_count = 4
cascade_split_lambda = 0.5
evsm_cutoff = "last_cascade"
far_cascade_update_rate = "every4_frames"
cube_face_update_rate = "every_frame"

[[nodes]]
id = "00000000-0000-4000-8000-000000000001"
name = "mirror-floor"
locked = false
visible = true
prefab = false
children = []

[nodes.transform]
translation = [
    0.0,
    0.0,
    0.0,
]
rotation = [
    0.0,
    0.0,
    0.0,
    1.0,
]
scale = [
    1.0,
    1.0,
    1.0,
]

[nodes.kind.mesh]
mesh = "00000000-0000-4000-8000-000000000001"
selected_variant = "00000000-0000-4000-8000-000000000040"

[[nodes.kind.mesh.material_variants]]
id = "00000000-0000-4000-8000-000000000040"
name = "mirror-floor"

[nodes.kind.mesh.material_variants.instance]
asset = "00000000-0000-4000-8000-000000000002"

[nodes.kind.mesh.material_variants.instance.inline]
label = ""
base_color = [
    0.949999988079071,
    0.9599999785423279,
    0.9700000286102295,
    1.0,
]
metallic = 1.0
roughness = 0.0
emissive = [
    0.0,
    0.0,
    0.0,
]
normal_scale = 1.0
occlusion_strength = 1.0
double_sided = false
vertex_colors_enabled = false
alpha_mode = "opaque"
shading = "pbr"

[nodes.kind.mesh.material_variants.instance.inline.extensions]

[nodes.kind.mesh.material_variants.instance.uniform_overrides]

[nodes.kind.mesh.material_variants.instance.texture_overrides]

[nodes.kind.mesh.material_variants.instance.buffer_overrides]

[nodes.kind.mesh.shadow]
cast = true
receive = true

[nodes.kind.mesh.lod]
enabled = true

[[nodes]]
id = "00000000-0000-4000-8000-000000000010"
name = "sphere-white"
locked = false
visible = true
prefab = false
children = []

[nodes.transform]
translation = [
    -2.4000000953674316,
    1.5,
    -1.2000000476837158,
]
rotation = [
    0.0,
    0.0,
    0.0,
    1.0,
]
scale = [
    1.0,
    1.0,
    1.0,
]

[nodes.kind.mesh]
mesh = "00000000-0000-4000-8000-000000000010"
selected_variant = "00000000-0000-4000-8000-000000000020"

[[nodes.kind.mesh.material_variants]]
id = "00000000-0000-4000-8000-000000000020"
name = "sphere-white"

[nodes.kind.mesh.material_variants.instance]
asset = "00000000-0000-4000-8000-000000000003"

[nodes.kind.mesh.material_variants.instance.inline]
label = ""
base_color = [
    0.019999999552965164,
    0.019999999552965164,
    0.019999999552965164,
    1.0,
]
metallic = 0.0
roughness = 0.699999988079071
emissive = [
    5.0,
    5.0,
    5.0,
]
normal_scale = 1.0
occlusion_strength = 1.0
double_sided = false
vertex_colors_enabled = false
alpha_mode = "opaque"
shading = "pbr"

[nodes.kind.mesh.material_variants.instance.inline.extensions]

[nodes.kind.mesh.material_variants.instance.uniform_overrides]

[nodes.kind.mesh.material_variants.instance.texture_overrides]

[nodes.kind.mesh.material_variants.instance.buffer_overrides]

[nodes.kind.mesh.shadow]
cast = true
receive = true

[nodes.kind.mesh.lod]
enabled = true

[[nodes]]
id = "00000000-0000-4000-8000-000000000011"
name = "box-red"
locked = false
visible = true
prefab = false
children = []

[nodes.transform]
translation = [
    0.4000000059604645,
    0.8999999761581421,
    -2.200000047683716,
]
rotation = [
    0.0,
    0.0,
    0.0,
    1.0,
]
scale = [
    1.0,
    1.0,
    1.0,
]

[nodes.kind.mesh]
mesh = "00000000-0000-4000-8000-000000000011"
selected_variant = "00000000-0000-4000-8000-000000000021"

[[nodes.kind.mesh.material_variants]]
id = "00000000-0000-4000-8000-000000000021"
name = "box-red"

[nodes.kind.mesh.material_variants.instance]
asset = "00000000-0000-4000-8000-000000000003"

[nodes.kind.mesh.material_variants.instance.inline]
label = ""
base_color = [
    0.019999999552965164,
    0.019999999552965164,
    0.019999999552965164,
    1.0,
]
metallic = 0.0
roughness = 0.699999988079071
emissive = [
    5.0,
    0.15000000596046448,
    0.15000000596046448,
]
normal_scale = 1.0
occlusion_strength = 1.0
double_sided = false
vertex_colors_enabled = false
alpha_mode = "opaque"
shading = "pbr"

[nodes.kind.mesh.material_variants.instance.inline.extensions]

[nodes.kind.mesh.material_variants.instance.uniform_overrides]

[nodes.kind.mesh.material_variants.instance.texture_overrides]

[nodes.kind.mesh.material_variants.instance.buffer_overrides]

[nodes.kind.mesh.shadow]
cast = true
receive = true

[nodes.kind.mesh.lod]
enabled = true

[[nodes]]
id = "00000000-0000-4000-8000-000000000012"
name = "torus-thin"
locked = false
visible = true
prefab = false
children = []

[nodes.transform]
translation = [
    2.5999999046325684,
    2.0,
    -1.0,
]
rotation = [
    0.0,
    0.0,
    0.0,
    1.0,
]
scale = [
    1.0,
    1.0,
    1.0,
]

[nodes.kind.mesh]
mesh = "00000000-0000-4000-8000-000000000012"
selected_variant = "00000000-0000-4000-8000-000000000022"

[[nodes.kind.mesh.material_variants]]
id = "00000000-0000-4000-8000-000000000022"
name = "torus-thin"

[nodes.kind.mesh.material_variants.instance]
asset = "00000000-0000-4000-8000-000000000003"

[nodes.kind.mesh.material_variants.instance.inline]
label = ""
base_color = [
    0.019999999552965164,
    0.019999999552965164,
    0.019999999552965164,
    1.0,
]
metallic = 0.0
roughness = 0.699999988079071
emissive = [
    0.4000000059604645,
    2.200000047683716,
    5.0,
]
normal_scale = 1.0
occlusion_strength = 1.0
double_sided = false
vertex_colors_enabled = false
alpha_mode = "opaque"
shading = "pbr"

[nodes.kind.mesh.material_variants.instance.inline.extensions]

[nodes.kind.mesh.material_variants.instance.uniform_overrides]

[nodes.kind.mesh.material_variants.instance.texture_overrides]

[nodes.kind.mesh.material_variants.instance.buffer_overrides]

[nodes.kind.mesh.shadow]
cast = true
receive = true

[nodes.kind.mesh.lod]
enabled = true

[[nodes]]
id = "00000000-0000-4000-8000-000000000013"
name = "sphere-touching"
locked = false
visible = true
prefab = false
children = []

[nodes.transform]
translation = [
    -5.199999809265137,
    0.800000011920929,
    -1.2000000476837158,
]
rotation = [
    0.0,
    0.0,
    0.0,
    1.0,
]
scale = [
    1.0,
    1.0,
    1.0,
]

[nodes.kind.mesh]
mesh = "00000000-0000-4000-8000-000000000013"
selected_variant = "00000000-0000-4000-8000-000000000023"

[[nodes.kind.mesh.material_variants]]
id = "00000000-0000-4000-8000-000000000023"
name = "sphere-touching"

[nodes.kind.mesh.material_variants.instance]
asset = "00000000-0000-4000-8000-000000000003"

[nodes.kind.mesh.material_variants.instance.inline]
label = ""
base_color = [
    0.019999999552965164,
    0.019999999552965164,
    0.019999999552965164,
    1.0,
]
metallic = 0.0
roughness = 0.699999988079071
emissive = [
    4.0,
    3.200000047683716,
    1.2000000476837158,
]
normal_scale = 1.0
occlusion_strength = 1.0
double_sided = false
vertex_colors_enabled = false
alpha_mode = "opaque"
shading = "pbr"

[nodes.kind.mesh.material_variants.instance.inline.extensions]

[nodes.kind.mesh.material_variants.instance.uniform_overrides]

[nodes.kind.mesh.material_variants.instance.texture_overrides]

[nodes.kind.mesh.material_variants.instance.buffer_overrides]

[nodes.kind.mesh.shadow]
cast = true
receive = true

[nodes.kind.mesh.lod]
enabled = true
