name = "untitled.awsm"
custom_materials = []
animations = []

[environment]
skybox = "built_in_default"
specular = "built_in_default"
irradiance = "built_in_default"

[shadows]
sscs_enabled = false
sscs_step_count = 16
sscs_step_world = 0.03999999910593033
sscs_thickness = 0.05000000074505806
sscs_directional_darkening = 0.3499999940395355
sscs_punctual_darkening = 0.8999999761581421
atlas_size = 4096
evsm_atlas_size = 2048
evsm_exponent = 10.0
evsm_blur_radius = 6
max_point_shadows = 8
point_shadow_resolution = 1024
debug_cascade_colors = false

[post_process]
tonemapping = "khronos_neutral_pbr"
bloom = false
dof = false
exposure = 0.0
bloom_threshold = 1.0
bloom_knee = 0.5
bloom_intensity = 1.0
bloom_scatter = 1.0

[post_process.ssr]
enabled = false
intensity = 1.0
max_distance = 100.0
thickness = 1.0
max_steps = 96
spread_cutoff = 0.6000000238418579
edge_fade = 0.10000000149011612
resolution_scale = 0.5
temporal = false
temporal_weight = 0.8999999761581421

[assets.00000000-0000-4000-8000-0000000000f0]
gltf_material_asset_ids = []
gltf_image_asset_ids = []
content_hash = "19c705f7e207384ca1ab01e0665601c051ca33c5848c03ce4fffad625b416b53"
texture_encoding = "webp"

[assets.00000000-0000-4000-8000-0000000000f0.source.texture.raster]
display_name = "AlphaBlendLabels.png"
color_kind = "albedo"

[assets.00000000-0000-4000-8000-00000000000b]
gltf_material_asset_ids = []
gltf_image_asset_ids = []
content_hash = ""

[assets.00000000-0000-4000-8000-00000000000b.source.mesh.primitive.box]
dims = [
    3.200000047683716,
    2.4000000953674316,
    0.05000000074505806,
]

[assets.00000000-0000-4000-8000-00000000000c]
gltf_material_asset_ids = []
gltf_image_asset_ids = []
content_hash = ""

[assets.00000000-0000-4000-8000-00000000000c.source.mesh.primitive.box]
dims = [
    3.200000047683716,
    2.4000000953674316,
    0.05000000074505806,
]

[assets.00000000-0000-4000-8000-00000000000a]
gltf_material_asset_ids = []
gltf_image_asset_ids = []
content_hash = ""

[assets.00000000-0000-4000-8000-00000000000a.source.mesh.primitive.box]
dims = [
    3.200000047683716,
    2.4000000953674316,
    0.05000000074505806,
]

[assets.00000000-0000-4000-8000-000000000001]
gltf_material_asset_ids = []
gltf_image_asset_ids = []
content_hash = ""

[assets.00000000-0000-4000-8000-000000000001.source.mesh.primitive.plane]
width = 12.0
depth = 12.0
segments_x = 1
segments_z = 1

[mixer]
layers = []

[[nodes]]
id = "14fa4fe0-19f2-4fdd-bfeb-2bb9b25feced"
name = "Directional Light"
locked = false
visible = true
prefab = false
children = []

[nodes.transform]
translation = [
    0.0,
    0.0,
    0.0,
]
rotation = [
    -0.4226182699203491,
    0.0,
    0.0,
    0.9063077569007874,
]
scale = [
    1.0,
    1.0,
    1.0,
]

[nodes.kind.light.directional]
color = [
    1.0,
    1.0,
    1.0,
]
intensity = 4.0

[nodes.kind.light.directional.shadow]
cast = true
depth_bias = 0.0010000000474974513
normal_bias = 0.0
resolution = 2048
hardness = "soft"
pcss_penumbra_scale = 1.0
kernel_slack = 0.0
shadow_samples = 16
max_distance = 0.0
cascade_count = 4
cascade_split_lambda = 0.5
evsm_cutoff = "last_cascade"
far_cascade_update_rate = "every4_frames"
cube_face_update_rate = "every_frame"

[[nodes]]
id = "00000000-0000-4000-8000-000000000001"
name = "floor"
locked = false
visible = true
prefab = false
children = []

[nodes.transform]
translation = [
    0.0,
    0.0,
    0.0,
]
rotation = [
    0.0,
    0.0,
    0.0,
    1.0,
]
scale = [
    1.0,
    1.0,
    1.0,
]

[nodes.kind.mesh]
mesh = "00000000-0000-4000-8000-000000000001"
selected_variant = "00000000-0000-4000-8000-000000000021"

[[nodes.kind.mesh.material_variants]]
id = "00000000-0000-4000-8000-000000000021"
name = "floor"

[nodes.kind.mesh.material_variants.instance]
asset = "00000000-0000-4000-8000-000000000005"

[nodes.kind.mesh.material_variants.instance.inline]
label = ""
base_color = [
    0.5,
    0.5,
    0.5199999809265137,
    1.0,
]
metallic = 0.0
roughness = 0.699999988079071
emissive = [
    0.0,
    0.0,
    0.0,
]
normal_scale = 1.0
occlusion_strength = 1.0
double_sided = false
vertex_colors_enabled = false
alpha_mode = "opaque"
shading = "pbr"

[nodes.kind.mesh.material_variants.instance.inline.extensions]

[nodes.kind.mesh.material_variants.instance.uniform_overrides]

[nodes.kind.mesh.material_variants.instance.texture_overrides]

[nodes.kind.mesh.material_variants.instance.buffer_overrides]

[nodes.kind.mesh.shadow]
cast = true
receive = true

[nodes.kind.mesh.lod]
enabled = true

[[nodes]]
id = "00000000-0000-4000-8000-00000000000a"
name = "mask-025"
locked = false
visible = true
prefab = false
children = []

[nodes.transform]
translation = [
    0.0,
    1.2999999523162842,
    2.200000047683716,
]
rotation = [
    0.0,
    0.0,
    0.0,
    1.0,
]
scale = [
    1.0,
    1.0,
    1.0,
]

[nodes.kind.mesh]
mesh = "00000000-0000-4000-8000-00000000000a"
selected_variant = "00000000-0000-4000-8000-00000000002a"

[[nodes.kind.mesh.material_variants]]
id = "00000000-0000-4000-8000-00000000002a"
name = "mask-025"

[nodes.kind.mesh.material_variants.instance]
asset = "00000000-0000-4000-8000-000000000002"

[nodes.kind.mesh.material_variants.instance.inline]
label = ""
base_color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
metallic = 0.0
roughness = 0.699999988079071
emissive = [
    0.0,
    0.0,
    0.0,
]
normal_scale = 1.0
occlusion_strength = 1.0
double_sided = false
vertex_colors_enabled = false
shading = "pbr"

[nodes.kind.mesh.material_variants.instance.inline.base_color_texture]
asset = "00000000-0000-4000-8000-0000000000f0"

[nodes.kind.mesh.material_variants.instance.inline.alpha_mode.mask]
cutoff = 0.25

[nodes.kind.mesh.material_variants.instance.inline.extensions]

[nodes.kind.mesh.material_variants.instance.uniform_overrides]

[nodes.kind.mesh.material_variants.instance.texture_overrides]

[nodes.kind.mesh.material_variants.instance.buffer_overrides]

[nodes.kind.mesh.shadow]
cast = true
receive = true

[nodes.kind.mesh.lod]
enabled = true

[[nodes]]
id = "00000000-0000-4000-8000-00000000000b"
name = "mask-075"
locked = false
visible = true
prefab = false
children = []

[nodes.transform]
translation = [
    0.0,
    1.2999999523162842,
    0.0,
]
rotation = [
    0.0,
    0.0,
    0.0,
    1.0,
]
scale = [
    1.0,
    1.0,
    1.0,
]

[nodes.kind.mesh]
mesh = "00000000-0000-4000-8000-00000000000b"
selected_variant = "00000000-0000-4000-8000-00000000002b"

[[nodes.kind.mesh.material_variants]]
id = "00000000-0000-4000-8000-00000000002b"
name = "mask-075"

[nodes.kind.mesh.material_variants.instance]
asset = "00000000-0000-4000-8000-000000000003"

[nodes.kind.mesh.material_variants.instance.inline]
label = ""
base_color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
metallic = 0.0
roughness = 0.699999988079071
emissive = [
    0.0,
    0.0,
    0.0,
]
normal_scale = 1.0
occlusion_strength = 1.0
double_sided = false
vertex_colors_enabled = false
shading = "pbr"

[nodes.kind.mesh.material_variants.instance.inline.base_color_texture]
asset = "00000000-0000-4000-8000-0000000000f0"

[nodes.kind.mesh.material_variants.instance.inline.alpha_mode.mask]
cutoff = 0.75

[nodes.kind.mesh.material_variants.instance.inline.extensions]

[nodes.kind.mesh.material_variants.instance.uniform_overrides]

[nodes.kind.mesh.material_variants.instance.texture_overrides]

[nodes.kind.mesh.material_variants.instance.buffer_overrides]

[nodes.kind.mesh.shadow]
cast = true
receive = true

[nodes.kind.mesh.lod]
enabled = true

[[nodes]]
id = "00000000-0000-4000-8000-00000000000c"
name = "blend-ref"
locked = false
visible = true
prefab = false
children = []

[nodes.transform]
translation = [
    0.0,
    1.2999999523162842,
    -2.200000047683716,
]
rotation = [
    0.0,
    0.0,
    0.0,
    1.0,
]
scale = [
    1.0,
    1.0,
    1.0,
]

[nodes.kind.mesh]
mesh = "00000000-0000-4000-8000-00000000000c"
selected_variant = "00000000-0000-4000-8000-00000000002c"

[[nodes.kind.mesh.material_variants]]
id = "00000000-0000-4000-8000-00000000002c"
name = "blend-ref"

[nodes.kind.mesh.material_variants.instance]
asset = "00000000-0000-4000-8000-000000000004"

[nodes.kind.mesh.material_variants.instance.inline]
label = ""
base_color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
metallic = 0.0
roughness = 0.699999988079071
emissive = [
    0.0,
    0.0,
    0.0,
]
normal_scale = 1.0
occlusion_strength = 1.0
double_sided = false
vertex_colors_enabled = false
alpha_mode = "blend"
shading = "pbr"

[nodes.kind.mesh.material_variants.instance.inline.base_color_texture]
asset = "00000000-0000-4000-8000-0000000000f0"

[nodes.kind.mesh.material_variants.instance.inline.extensions]

[nodes.kind.mesh.material_variants.instance.uniform_overrides]

[nodes.kind.mesh.material_variants.instance.texture_overrides]

[nodes.kind.mesh.material_variants.instance.buffer_overrides]

[nodes.kind.mesh.shadow]
cast = true
receive = true

[nodes.kind.mesh.lod]
enabled = true
