name = "untitled.awsm"
custom_materials = []
animations = []

[environment]
skybox = "built_in_default"
specular = "built_in_default"
irradiance = "built_in_default"

[shadows]
sscs_enabled = false
sscs_step_count = 16
sscs_step_world = 0.03999999910593033
sscs_thickness = 0.05000000074505806
sscs_directional_darkening = 0.3499999940395355
sscs_punctual_darkening = 0.8999999761581421
atlas_size = 4096
evsm_atlas_size = 2048
evsm_exponent = 10.0
evsm_blur_radius = 6
max_point_shadows = 8
point_shadow_resolution = 1024
debug_cascade_colors = false

[post_process]
tonemapping = "khronos_neutral_pbr"
bloom = false
dof = false
exposure = 0.0
bloom_threshold = 1.0
bloom_knee = 0.5
bloom_intensity = 1.0
bloom_scatter = 1.0

[post_process.ssr]
enabled = false
intensity = 1.0
max_distance = 100.0
thickness = 1.0
max_steps = 96
spread_cutoff = 0.6000000238418579
edge_fade = 0.10000000149011612
resolution_scale = 0.5
temporal = false
temporal_weight = 0.8999999761581421

[assets.00000000-0000-4000-8000-0000000000f1]
gltf_material_asset_ids = []
gltf_image_asset_ids = []
content_hash = ""
texture_encoding = "webp"

[assets.00000000-0000-4000-8000-0000000000f1.source.texture.procedural.checker]
width = 512
height = 512
cells_x = 8
cells_y = 8
color_a = [
    0.8100000023841858,
    0.8299999833106995,
    0.8500000238418579,
    1.0,
]
color_b = [
    0.1599999964237213,
    0.18000000715255737,
    0.20000000298023224,
    1.0,
]

[assets.00000000-0000-4000-8000-000000000010]
gltf_material_asset_ids = []
gltf_image_asset_ids = []
content_hash = ""

[assets.00000000-0000-4000-8000-000000000010.source.mesh.primitive.box]
dims = [
    1.399999976158142,
    1.399999976158142,
    1.399999976158142,
]

[assets.00000000-0000-4000-8000-000000000001]
gltf_material_asset_ids = []
gltf_image_asset_ids = []
content_hash = ""

[assets.00000000-0000-4000-8000-000000000001.source.mesh.primitive.plane]
width = 14.0
depth = 14.0
segments_x = 1
segments_z = 1

[mixer]
layers = []

[[nodes]]
id = "1009116f-8657-4337-a88b-1ff4ea6225ea"
name = "Directional Light"
locked = false
visible = true
prefab = false
children = []

[nodes.transform]
translation = [
    0.0,
    0.0,
    0.0,
]
rotation = [
    -0.4226182699203491,
    0.0,
    0.0,
    0.9063077569007874,
]
scale = [
    1.0,
    1.0,
    1.0,
]

[nodes.kind.light.directional]
color = [
    1.0,
    1.0,
    1.0,
]
intensity = 4.0

[nodes.kind.light.directional.shadow]
cast = true
depth_bias = 0.0010000000474974513
normal_bias = 0.0
resolution = 2048
hardness = "soft"
pcss_penumbra_scale = 1.0
kernel_slack = 0.0
shadow_samples = 16
max_distance = 0.0
cascade_count = 4
cascade_split_lambda = 0.5
evsm_cutoff = "last_cascade"
far_cascade_update_rate = "every4_frames"
cube_face_update_rate = "every_frame"

[[nodes]]
id = "00000000-0000-4000-8000-000000000001"
name = "Plane"
locked = false
visible = true
prefab = false
children = []

[nodes.transform]
translation = [
    0.0,
    0.0,
    0.0,
]
rotation = [
    0.0,
    0.0,
    0.0,
    1.0,
]
scale = [
    1.0,
    1.0,
    1.0,
]

[nodes.kind.mesh]
mesh = "00000000-0000-4000-8000-000000000001"
selected_variant = "00000000-0000-4000-8000-000000000040"

[[nodes.kind.mesh.material_variants]]
id = "00000000-0000-4000-8000-000000000040"
name = "floor"

[nodes.kind.mesh.material_variants.instance]
asset = "00000000-0000-4000-8000-000000000002"

[nodes.kind.mesh.material_variants.instance.inline]
label = ""
base_color = [
    0.4000000059604645,
    0.41999998688697815,
    0.44999998807907104,
    1.0,
]
metallic = 0.0
roughness = 0.699999988079071
emissive = [
    0.0,
    0.0,
    0.0,
]
normal_scale = 1.0
occlusion_strength = 1.0
double_sided = false
vertex_colors_enabled = false
alpha_mode = "opaque"
shading = "pbr"

[nodes.kind.mesh.material_variants.instance.inline.extensions]

[nodes.kind.mesh.material_variants.instance.uniform_overrides]

[nodes.kind.mesh.material_variants.instance.texture_overrides]

[nodes.kind.mesh.material_variants.instance.buffer_overrides]

[nodes.kind.mesh.shadow]
cast = true
receive = true

[nodes.kind.mesh.lod]
enabled = true

[[nodes]]
id = "00000000-0000-4000-8000-000000000010"
name = "source-box"
locked = false
visible = true
prefab = true
children = []

[nodes.transform]
translation = [
    -3.0,
    0.699999988079071,
    -3.0,
]
rotation = [
    0.0,
    0.0,
    0.0,
    1.0,
]
scale = [
    1.0,
    1.0,
    1.0,
]

[nodes.kind.mesh]
mesh = "00000000-0000-4000-8000-000000000010"
selected_variant = "00000000-0000-4000-8000-000000000041"

[[nodes.kind.mesh.material_variants]]
id = "00000000-0000-4000-8000-000000000041"
name = "box-mat"

[nodes.kind.mesh.material_variants.instance]
asset = "00000000-0000-4000-8000-000000000003"

[nodes.kind.mesh.material_variants.instance.inline]
label = ""
base_color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
metallic = 0.0
roughness = 0.699999988079071
emissive = [
    0.0,
    0.0,
    0.0,
]
normal_scale = 1.0
occlusion_strength = 1.0
double_sided = false
vertex_colors_enabled = false
alpha_mode = "opaque"
shading = "pbr"

[nodes.kind.mesh.material_variants.instance.inline.base_color_texture]
asset = "00000000-0000-4000-8000-0000000000f1"

[nodes.kind.mesh.material_variants.instance.inline.extensions]

[nodes.kind.mesh.material_variants.instance.uniform_overrides]

[nodes.kind.mesh.material_variants.instance.texture_overrides]

[nodes.kind.mesh.material_variants.instance.buffer_overrides]

[nodes.kind.mesh.shadow]
cast = true
receive = true

[nodes.kind.mesh.lod]
enabled = true

[[nodes]]
id = "79eb7ff6-8055-4915-8798-06374a2cddd7"
name = "source-box"
locked = false
visible = true
prefab = true
children = []

[nodes.transform]
translation = [
    0.0,
    0.699999988079071,
    -3.0,
]
rotation = [
    0.0,
    0.0,
    0.0,
    1.0,
]
scale = [
    1.0,
    1.0,
    1.0,
]

[nodes.kind.mesh]
mesh = "00000000-0000-4000-8000-000000000010"
selected_variant = "00000000-0000-4000-8000-000000000041"

[[nodes.kind.mesh.material_variants]]
id = "00000000-0000-4000-8000-000000000041"
name = "box-mat"

[nodes.kind.mesh.material_variants.instance]
asset = "00000000-0000-4000-8000-000000000003"

[nodes.kind.mesh.material_variants.instance.inline]
label = ""
base_color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
metallic = 0.0
roughness = 0.699999988079071
emissive = [
    0.0,
    0.0,
    0.0,
]
normal_scale = 1.0
occlusion_strength = 1.0
double_sided = false
vertex_colors_enabled = false
alpha_mode = "opaque"
shading = "pbr"

[nodes.kind.mesh.material_variants.instance.inline.base_color_texture]
asset = "00000000-0000-4000-8000-0000000000f1"

[nodes.kind.mesh.material_variants.instance.inline.extensions]

[nodes.kind.mesh.material_variants.instance.uniform_overrides]

[nodes.kind.mesh.material_variants.instance.texture_overrides]

[nodes.kind.mesh.material_variants.instance.buffer_overrides]

[nodes.kind.mesh.shadow]
cast = true
receive = true

[nodes.kind.mesh.lod]
enabled = true

[[nodes]]
id = "dcba6ad1-9391-46ac-aeca-d5f7c5ce8128"
name = "source-box"
locked = false
visible = true
prefab = true
children = []

[nodes.transform]
translation = [
    3.0,
    0.699999988079071,
    -3.0,
]
rotation = [
    0.0,
    0.0,
    0.0,
    1.0,
]
scale = [
    1.0,
    1.0,
    1.0,
]

[nodes.kind.mesh]
mesh = "00000000-0000-4000-8000-000000000010"
selected_variant = "00000000-0000-4000-8000-000000000041"

[[nodes.kind.mesh.material_variants]]
id = "00000000-0000-4000-8000-000000000041"
name = "box-mat"

[nodes.kind.mesh.material_variants.instance]
asset = "00000000-0000-4000-8000-000000000003"

[nodes.kind.mesh.material_variants.instance.inline]
label = ""
base_color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
metallic = 0.0
roughness = 0.699999988079071
emissive = [
    0.0,
    0.0,
    0.0,
]
normal_scale = 1.0
occlusion_strength = 1.0
double_sided = false
vertex_colors_enabled = false
alpha_mode = "opaque"
shading = "pbr"

[nodes.kind.mesh.material_variants.instance.inline.base_color_texture]
asset = "00000000-0000-4000-8000-0000000000f1"

[nodes.kind.mesh.material_variants.instance.inline.extensions]

[nodes.kind.mesh.material_variants.instance.uniform_overrides]

[nodes.kind.mesh.material_variants.instance.texture_overrides]

[nodes.kind.mesh.material_variants.instance.buffer_overrides]

[nodes.kind.mesh.shadow]
cast = true
receive = true

[nodes.kind.mesh.lod]
enabled = true

[[nodes]]
id = "45dbf4f9-af47-4f17-aebd-a939cf72fe9c"
name = "source-box"
locked = false
visible = true
prefab = true
children = []

[nodes.transform]
translation = [
    -1.5,
    0.699999988079071,
    0.0,
]
rotation = [
    0.0,
    0.0,
    0.0,
    1.0,
]
scale = [
    1.0,
    1.0,
    1.0,
]

[nodes.kind.mesh]
mesh = "00000000-0000-4000-8000-000000000010"
selected_variant = "00000000-0000-4000-8000-000000000041"

[[nodes.kind.mesh.material_variants]]
id = "00000000-0000-4000-8000-000000000041"
name = "box-mat"

[nodes.kind.mesh.material_variants.instance]
asset = "00000000-0000-4000-8000-000000000003"

[nodes.kind.mesh.material_variants.instance.inline]
label = ""
base_color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
metallic = 0.0
roughness = 0.699999988079071
emissive = [
    0.0,
    0.0,
    0.0,
]
normal_scale = 1.0
occlusion_strength = 1.0
double_sided = false
vertex_colors_enabled = false
alpha_mode = "opaque"
shading = "pbr"

[nodes.kind.mesh.material_variants.instance.inline.base_color_texture]
asset = "00000000-0000-4000-8000-0000000000f1"

[nodes.kind.mesh.material_variants.instance.inline.extensions]

[nodes.kind.mesh.material_variants.instance.uniform_overrides]

[nodes.kind.mesh.material_variants.instance.texture_overrides]

[nodes.kind.mesh.material_variants.instance.buffer_overrides]

[nodes.kind.mesh.shadow]
cast = true
receive = true

[nodes.kind.mesh.lod]
enabled = true

[[nodes]]
id = "68f268ac-8c67-4047-8ca8-73c65c91345c"
name = "source-box"
locked = false
visible = true
prefab = true
children = []

[nodes.transform]
translation = [
    1.5,
    0.699999988079071,
    0.0,
]
rotation = [
    0.0,
    0.0,
    0.0,
    1.0,
]
scale = [
    1.0,
    1.0,
    1.0,
]

[nodes.kind.mesh]
mesh = "00000000-0000-4000-8000-000000000010"
selected_variant = "00000000-0000-4000-8000-000000000041"

[[nodes.kind.mesh.material_variants]]
id = "00000000-0000-4000-8000-000000000041"
name = "box-mat"

[nodes.kind.mesh.material_variants.instance]
asset = "00000000-0000-4000-8000-000000000003"

[nodes.kind.mesh.material_variants.instance.inline]
label = ""
base_color = [
    1.0,
    1.0,
    1.0,
    1.0,
]
metallic = 0.0
roughness = 0.699999988079071
emissive = [
    0.0,
    0.0,
    0.0,
]
normal_scale = 1.0
occlusion_strength = 1.0
double_sided = false
vertex_colors_enabled = false
alpha_mode = "opaque"
shading = "pbr"

[nodes.kind.mesh.material_variants.instance.inline.base_color_texture]
asset = "00000000-0000-4000-8000-0000000000f1"

[nodes.kind.mesh.material_variants.instance.inline.extensions]

[nodes.kind.mesh.material_variants.instance.uniform_overrides]

[nodes.kind.mesh.material_variants.instance.texture_overrides]

[nodes.kind.mesh.material_variants.instance.buffer_overrides]

[nodes.kind.mesh.shadow]
cast = true
receive = true

[nodes.kind.mesh.lod]
enabled = true
